### ISSUE TITLE
add prefix for AreaTrigger, ClickTrigger, and WalkTrigger

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#145]
It was a design flaw, to be honest.

The conversion will need extream caution

**Comment by gmalone** [comment]
As suggested on Discord #suggestions channel:
Would be super useful if Click  trigger "nnn.trg" **filename format could be changed** to **allow a meaningful prefix or suffix added**, without violating the `<worldname>@<x><y><z>` by leaving that part at the start or end of the filename.
**Example:**  instead of `myworld@0,0,0.trg`, allow something like `waterhole-myworld@0,0,0.trg` or  `myworld@0,0,0-waterhole` -- **you just parse the part you need**.
Surely we've all looked at the list of click trg files and gotten bewildered by which is which... no?  We lose time hunting/searching for the file we need to work on.
Kindly consider this, would be quite impactful in a good way.

**Comment by wysohn** [comment]
@gmalone 
Sounds like a great idea.

What I was think is to convert all the previous trg scripts into two files: source and yml. You can think of how InventoryTrigger is saved. 

But your idea seems to be more easy to implement. Which one would you like better in your perspective?

**Comment by gmalone** [comment]
A PREFIX would definitely be preferable because then you could sort them alphabetically and get automatic (and useful) grouping of similarly named locations and purposes.  Thanks for doing this.  Of course, all previously existing click trg files should still work... the parsing takes care of that either way.
