### ISSUE TITLE
PortalCreateEvent and EntityCreatePortalEvent is not hooked?

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#194]

**Comment by wysohn** [comment]
It's not implemented in Sponge https://github.com/SpongePowered/SpongeCommon/pull/1608

Just checked that the event is not firing at all

**Comment by wysohn** [comment]
It seems like spigot team removed the event itself, yet they are going to add it soon.

Cannot do anything atm

https://github.com/Multiverse/Multiverse-Core/issues/2000

**Comment by ryantheleach** [comment]
You shouldn't even be looking at Sponge, as Multiverse is a Spigot plugin.

Sponge does not have compatibility with Bukkit plugins, and any project that has attempted to do so (without a 3rd party intermediate API has failed)

Sponge is a completely separate project, with it's own ecosystem of plugins.

(Only commenting because I noticed, to prevent others from getting confused.)

**Comment by wysohn** [comment]
@ryantheleach 
Thank you!

Though, this plugin support both Sponge and Spigot, so I have to count on both APIs.

I just use it as reminder for myself so I can come back and fix it whenever the API is ready for it.

Sadly, both Spigot and Sponge does not support portal creation events atm :/
