### ISSUE TITLE
PAPI Expansion for TR

### ISSUE THREAD

**Issue by rkdrns4747** [wysohn/TriggerReactor#212]
create a PAPI Expansion for Trigger Reactor that can provide a Global Variable value. 

e.g.)

%tr_var_{variable name}%
%tr_version%

**Comment by rkdrns4747** [comment]
Done in 86c1450

**Comment by wysohn** [comment]
@rkdrns4747 
I've made some minor changes.

Let me know if something is not right.

Plus, don't forget the case where the variable has children

For example, %tr_somenum% will be parsed because it's not a tree but a single value,

but there are some cases where we can use the hierarchy of variables like `"some.var.iable," and this patch doesn't support it.

---
**Suggestion**
Make it automatically convert `_` sign to `.`, so it can be understood of a nested variable.

For example, `some.var.iable` in TriggerReactor can be correspond to `%tr_some_var_riable%`

**Comment by rkdrns4747** [comment]
@wysohn is there any unacceptable characters for global variable?

**Comment by rkdrns4747** [comment]
Something like ^ or ★

**Comment by wysohn** [comment]
@rkdrns4747 
Lexer will reject any character that's not in the character list.
https://github.com/wysohn/TriggerReactor/blob/4773612019eddc0bf9afc0fa781141fb6ec90770/core/src/main/java/io/github/wysohn/triggerreactor/core/script/lexer/Lexer.java#L34

And obviously the numerics and etc. Character in String is an exception though.

**Comment by rkdrns4747** [comment]
@wysohn Great.

**Comment by wysohn** [comment]
@rkdrns4747 
Is this commit done? Please move the card if it is. It's under 'In Progress' now.

https://github.com/wysohn/TriggerReactor/projects/3

**Comment by rkdrns4747** [comment]
@wysohn sry I forgot to move this.
It's on 3.0.0v3-Beta now.
