### ISSUE TITLE
Convert Executors and Placeholders according to #198

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#231]
Need to convert current codes following the format introduced in #198

**Comment by gerzytet** [comment]
I’m afraid that doing so will have little to no benefit.
While it would be pleasant if all the executors were automatically validated, users don’t gain anything from using an automatically validated executor rather than a manually validated one.
The error messages are different, but the errors in the old code were written well.  Most of the old code itself was written well too.
Automatic validation only helps users indirectly because writing executors becomes less painful so we have more motivation to do it and include more executors in new releases.  In other words, automatic validation is only a tool for writing executors (for now), and the end product is the same.
If you do change the old code, you’ll also have to change all the unit tests as well.
I think it’s more trouble than it’s worth.
@wysohn

**Comment by gerzytet** [comment]
I did convert a few when validation was first being worked on, but only because I wanted to create examples of its usage.  I don’t plan to do this to every executor and placeholder
