### ISSUE TITLE
Indicate which executors require sync mode

### ISSUE THREAD

**Issue by gerzytet** [wysohn/TriggerReactor#240]
The Sync page contains some general guideline so to determine which operations require sync mode, but most people don’t read this page Andnnsn it isn’t always clear which executors require sync.
We should add markers to the executors that require sync mode.

**Comment by wysohn** [comment]
Can you clarify what it means by executors require sync mode?

Executors run only in server thread, so it always syncs regardless of Triggers.

**Comment by gerzytet** [comment]
Some executors have to execute with the server thread, like #SETBLOCK, these need to be marked specificaly

**Comment by wysohn** [comment]
@gerzytet 
By the design itself, anything runs as Executor or Placeholder runs in server thread.

Code interpretation is async though.

If you are talking about the direct method invocation, then sync mode is required for sure, but Executor and Placeholder does not since they run in server thread anyway.

**Comment by gerzytet** [comment]
@wysohn 
Didn't know that, oops.
