### ISSUE TITLE
Playing Sound to a Players Killer on PlayerDeathEvent

### ISSUE THREAD

**Issue by DontActLikeMe** [wysohn/TriggerReactor#30]
Thanks for your reply on your bukkit page. I'm actually having an issue playing a sound to the killer of a player on a player death event. Im having killstreaks as you saw in our private messages on bukkit, and im trying to add sounds upon the killstreak being acquired. 
I was using
dead = event.getEntity()
killer = dead.getKiller()
#SOUND killer.getLocation() "ENTITY_BLAZE_DEATH" 5.0 1.0
I can understand why it wont work. It requires a player location not an entity location and the cause of a player death could be from an entity. Im just wondering how you would make this work. Thank you!

**Comment by wysohn** [comment]
You almost hit the right point, but there is another reason why #SOUND didn't work as intended.

Because how Executor was made, it extracts variable as much as possible from the event class itself.

In fact, #SOUND is designed to used when there is a 'player' variable exists, and the 'player' variable here is the player who got killed not the killer.

To go around with this problem, you have to manually invoke the method of killer's [playSound()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound-org.bukkit.Location-java.lang.String-float-float-)

This way, you will be able to play sound only for the killer.

But make sure to check if the killer is Player, as any entity can fire PlayerDeathEvent; the playSound() only exists for the Player; therefore, it will make error if the killer is not Player.

To check that, you may use IF statement

    IF killer.getType().name() == PLAYER
        killer.playSound(...)
    ENDIF

**Comment by wysohn** [comment]
Umm actually, you can't do that as of now.

As you can see, the playSound() only accepts float, not double.

to work around on this one, you first save value and use floatValue() method.

    volume = 1.0
    pitch = 1.0
    killer.playSound(someloc, sound, volume.floatValue(), pitch.floatValue())

**Comment by wysohn** [comment]
Or, really, you can create your own Executor xD

I think this way will work better

All you need to do is copy everything in the SOUND executor and change 'player' variable into 'player.getKiller()'

Maybe you can name it like SOUNDKILLER or something

    #SOUNDKILLER killer.getLocation() "ENTITY_BLAZE_DEATH" 5.0 1.0

**Comment by DontActLikeMe** [comment]
Ok thank you so much for all your help. Im definitely gonna try all that you just put down.

**Comment by DontActLikeMe** [comment]
i tried both and was getting an error. I made your executor say player.getKiller() and i also did the IF statement but it said it did not recognize the value ENTITY_BLAZE_DEATH. this is how i had it.
dead.getKiller().playSound(dead.getKiller().getLocation(),Sound.ENTITY_BLAZE_DEATH,5,1) i also tried
dead.getKiller().playSound(dead.getKiller().getLocation(),ENTITY_BLAZE_DEATH, 5,1) it can always be me of course im human lol but i looked over each, a dozen times before coming back to you. I wanted to make sure it wasn't just me. I researched links on the play sound parameters to make sure i had them right.

**Comment by wysohn** [comment]
Ok, the thing is that TriggerReactor doesn't recognize static access xD

So it's nothing wrong with you as you tried the Java thing, but it was too much for TriggerReactor.

So what's the solution? I recently updated it to version 1.3.2, and this version support conversion from String to Enum.

For example,

    dead.getKiller().playSound(dead.getKiller().getLocation(), "ENTITY_BLAZE_DEATH", 5, 1)

will work, because now TriggerReactor first check the parameter of method and see if it is Enum, then it will try to convert String value to Enum corresponding to the provided String. So the String you provide here must be exactly matching name with the one in the whatever enum you are trying to use.

I think the 5, 1 part will cause some error as the method only accepts float value. Did you try it? If that works then it's all good, but if it doesn't, try (5.0).floatValue()

Let me know if something still doesn't seem to work.

(Dont forget to get the latest version! I also added wiki about enum conversion, so you might want to take a look)
